version: "3"

services:
  api:
    container_name: api.bookisia
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/var/www/.env
    ports:
      - "9000:80"
    networks:
      - bookisia

  mysql:
    container_name: bookisia-mysql-server
    image: 'mysql/mysql-server:8.0'
    ports:
      - '9306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './.docker/prod/mysql:/var/lib/mysql'
    networks:
      - bookisia

networks:
  bookisia:
    driver: bridge
