version: 0.2


phases:
  install:
    runtime-versions:
      php: 8.1
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - TAG="latest"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - docker build --tag "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"bookisia-api","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
