version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_CURRENT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_CURRENT_REGION.amazonaws.com
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
      - aws s3 cp s3://bookisia-private/env_files/frontpage/frontpage.qa.env .env
  build:
    commands:
      - docker build --tag "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"bookisia-frontpage","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
